apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: imp-gateway
  name: imp-gateway
  namespace: admap-dev
spec:
  selector:
    matchLabels:
      app: imp-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: imp-gateway
    spec:
      nodeSelector:
        node: node1
      hostNetwork: true
      containers:
      - name: imp-gateway
        image: 10.43.75.137/admap-dev/imp-gateway:20200210150908
        ports:
        - containerPort: 13003
        volumeMounts:
        - name: imp-gateway-log
          mountPath: /data/logs/imp-gateway
      - image: elastic/filebeat:7.4.2
        name: filebeat
        imagePullPolicy: IfNotPresent
        args: [
          "-c", "/etc/filebeat/filebeat.yml",
          "-e",
        ]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: pod_name
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: imp-gateway-log
          mountPath: /log
        - name: config
          mountPath: /etc/filebeat/
        - name: data
          mountPath: /usr/share/filebeat/data
      volumes:
      - name: imp-gateway-log
        emptyDir: {}
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
      - name: config
        configMap:
          name: imp-gateway-filebeat-config
